Update update_genomes

diff --git a/cruize_scripts/update_genomes b/cruize_scripts/update_genomes
--- a/cruize_scripts/update_genomes
+++ b/cruize_scripts/update_genomes
@@ -11,7 +11,34 @@ cols=$(head -n 1 /tmp/dbDb.tsv)
 tail -n+2 /tmp/dbDb.tsv | while IFS=$'\t' read -r $cols
 do
   if [ $gid != "NA" ] && [ $active -eq 1 ]; then
+    
+    mkdir -p $nibPath
+    mkdir -p $nibPath/html
+    mkdir -p $nibPath/bbi
+    
+    if [ ! -f $nibPath/genome.2bit ]; then
+      if [ ! -f $nibPath/genome.fa]; then
+        >&2 echo "genome fasta not found at $nibPath/genome.fa"
+        exit 1
+      elif [ ! -f $nibPath/genome.2bit ]; then
+        faToTwoBit $nibPath/genome.fa $nibPath/genome.2bit
+      fi
+      
+      if [ ! -f $nibPath/chromInfo.tab ]; then
+        twoBitInfo $nibPath/genome.2bit stdout | awk "{printf \"%s\t%s\t$nibPath/genome.2bit\n\", \$1,\$2}" > $nibPath/chromInfo.tab
+      fi
+      
+      if [ ! -f $nibPath/genome.chrom.sizes ]; then
+        cut -f 1,2 $nibPath/chromInfo.tab | sort -k1,1 > $nibPath/genome.chrom.sizes
+      fi
+      
+      if [ ! -f $nibPath/cytoband.bed ]; then
+        awk '{print $1"\t"0"\t"$2"\t""\t""gneg"}' $nibPath/genome.chrom.sizes | sort -k1,1 -k2,2n > $nibPath/cytoband.bed
+      fi
+    fi
 
+    
+    
     echo "<h2>Summary</h2> $summary <hr>" >  $htmlPath
     echo "<h2>Credits</h2> $credits <hr>" >> $htmlPath
     ln -sf /gbdb $nibDir/gbdb # to address a bug where web blat looks for gbdb in nibDir
@@ -80,7 +107,6 @@ do
     done
 
     #######################################
-
 
     # create track database file from spreadsheet
     awk -F "\t" '{if(NR==1){split($0,xx,"\t"); nf=NF} ; if(NR>1 && $1==1){for (i = 1; i <= nf; i++) print xx[i]" "$i; print ""  }}' \
